### ISSUE TITLE
Survey copying fails

### ISSUE THREAD

**Issue by rumca** [akvo/akvo-flow#1354]
When copying a survey it seems like it initially works - the copied Survey appears in the dashboard, and the forms are also present. However on closer inspection none of the question groups have actually been copied across. I had a look in the logs and the following errors have been thrown:

```
I 2015-07-23 10:19:29.322
org.waterforpeople.mapping.app.web.DataProcessorRestServlet copySurvey: Copying 1 `QuestionGroup`
E 2015-07-23 10:19:29.527
com.gallatinsystems.framework.rest.AbstractRestApiServlet executeRequest: Could not execute rest request
org.springframework.beans.FatalBeanException: Could not copy properties from source to target; nested exception is java.lang.reflect.InvocationTargetException
	at org.springframework.beans.BeanUtils.copyProperties(BeanUtils.java:620)
	at org.springframework.beans.BeanUtils.copyProperties(BeanUtils.java:570)
	at com.gallatinsystems.survey.dao.SurveyUtils.shallowCopy(SurveyUtils.java:457)
	at org.waterforpeople.mapping.app.web.DataProcessorRestServlet.copySurvey(DataProcessorRestServlet.java:557)
	at org.waterforpeople.mapping.app.web.DataProcessorRestServlet.handleRequest(DataProcessorRestServlet.java:129)
	at com.gallatinsystems.framework.rest.AbstractRestApiServlet.executeRequest(AbstractRestApiServlet.java:85)
	at com.gallatinsystems.framework.rest.AbstractRestApiServlet.doPost(AbstractRestApiServlet.java:61)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:637)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
	at com.gallatinsystems.framework.servlet.PersistenceFilter.doFilter(PersistenceFilter.java:71)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:118)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:84)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:113)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:103)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:113)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:54)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:45)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.waterforpeople.mapping.app.web.rest.security.GaeAuthenticationFilter.doFilter(GaeAuthenticationFilter.java:92)
```
```
I 2015-07-23 10:20:09.709
org.waterforpeople.mapping.app.web.DataProcessorRestServlet copySurvey: Copying 1 `QuestionGroup`
E 2015-07-23 10:20:10.774
org.akvo.flow.events.EventLogger sendNotification: Unified log notification failed with status code: 405
E 2015-07-23 10:20:10.779
com.gallatinsystems.framework.rest.AbstractRestApiServlet executeRequest: Could not execute rest request
org.springframework.beans.FatalBeanException: Could not copy properties from source to target; nested exception is java.lang.reflect.InvocationTargetException
	at org.springframework.beans.BeanUtils.copyProperties(BeanUtils.java:620)
	at org.springframework.beans.BeanUtils.copyProperties(BeanUtils.java:570)
	at com.gallatinsystems.survey.dao.SurveyUtils.shallowCopy(SurveyUtils.java:457)
	at org.waterforpeople.mapping.app.web.DataProcessorRestServlet.copySurvey(DataProcessorRestServlet.java:557)
	at org.waterforpeople.mapping.app.web.DataProcessorRestServlet.handleRequest(DataProcessorRestServlet.java:129)
	at com.gallatinsystems.framework.rest.AbstractRestApiServlet.executeRequest(AbstractRestApiServlet.java:85)
	at com.gallatinsystems.framework.rest.AbstractRestApiServlet.doPost(AbstractRestApiServlet.java:61)
```

**Comment by muloem** [comment]
The exception occurs while trying to copy the new `ancestorIds` property.

**Comment by rumca** [comment]
Copying now works again as expected :+1:
