### ISSUE TITLE
Fix NPE when stored counts are null

### ISSUE THREAD

**Issue by iperdomo** [akvo/akvo-flow#1772]
```
Failed to process zip file:bb54c05e-ea73-4a83-ab48-94ca047f76f8.zip : null
java.lang.NullPointerException
    at org.waterforpeople.mapping.domain.SurveyInstance.updateSummaryCounts(SurveyInstance.java:396)
    at org.waterforpeople.mapping.dao.SurveyInstanceDAO.save(SurveyInstanceDAO.java:159)
    at org.waterforpeople.mapping.app.web.TaskServlet.processFile(TaskServlet.java:204)
    at org.waterforpeople.mapping.app.web.TaskServlet.ingestFile(TaskServlet.java:388)
    at org.waterforpeople.mapping.app.web.TaskServlet.handleRequest(TaskServlet.java:354)
    at com.gallatinsystems.framework.rest.AbstractRestApiServlet.executeRequest(AbstractRestApiServlet.java:85)
    at com.gallatinsystems.framework.rest.AbstractRestApiServlet.doPost(AbstractRestApiServlet.java:61)
   [...]
```

**Comment by janagombitova** [comment]
@iperdomo could you add a test plan for the issue? Thanks

**Comment by iperdomo** [comment]
@janagombitova unfortunately i don't have a way of reproducing the error. It just annoying to have those `NullPointerException` in the email :wink: 

Some of us are recipients of error stack traces when something goes wrong processing a data file (the _stacktrace_ copy i pasted in the issue).

I can forward some emails with the same error.

**Comment by osg74** [comment]
Small enough fix, which should stop error emails from this particular code fragment.

**Comment by janagombitova** [comment]
@osg74 I do not know how to check this one as I am not in the email list (was one way how I thought I can test it out). Can you please decide on if this implementation is ready for releasing? Thanks

**Comment by osg74** [comment]
Should be ready for release -- I've added myself to the mailing list to catch any similar errors in future.
