### ISSUE TITLE
Bootstrap files not generated for surveys without cascading question types

### ISSUE THREAD

**Issue by muloem** [akvo/akvo-flow#2078]
During generation of bootstrap files, an exception is incurred for forms that do not contain any cascading questions, that causes the bootstrap file to not be generated correctly.

```
     [java] SEVERE: Could not include survey id 5348024557502464
     [java] 
     [java] java.lang.NullPointerException
     [java] 	at com.gallatinsystems.survey.dao.QuestionDao.listQuestionsInOrder(QuestionDao.java:230)
     [java] 	at org.waterforpeople.mapping.app.web.BootstrapGeneratorServlet.getSurveyResources(BootstrapGeneratorServlet.java:189)
     [java] 	at org.waterforpeople.mapping.app.web.BootstrapGeneratorServlet.generateFile(BootstrapGeneratorServlet.java:132)
     [java] 	at org.waterforpeople.mapping.app.web.BootstrapGeneratorServlet.handleRequest(BootstrapGeneratorServlet.java:100)
```

**Comment by janagombitova** [comment]
Works like a charm! 👍
