### ISSUE TITLE
NPE in updateSummaryCounts

### ISSUE THREAD

**Issue by stellanl** [akvo/akvo-flow#2107]
We get an NPE here if the count is 0, during data ingestion (which generates a stack dump email):

```
java.lang.NullPointerException
    at org.waterforpeople.mapping.domain.SurveyInstance.updateSummaryCounts(SurveyInstance.java:396)
```

**Comment by stellanl** [comment]
This one is a bit weird, as the null  object is the first element in a list (that is not empty). I don't see why SurveyQuestionSummaryDao.listByResponse() would return a null element in the list.

**Comment by stellanl** [comment]
We also get a NPE here: 
java.lang.NullPointerException
    at org.waterforpeople.mapping.dao.SurveyInstanceDAO.save(SurveyInstanceDAO.java:125)
    at org.waterforpeople.mapping.app.web.TaskServlet.processFile(TaskServlet.java:204)
    at org.waterforpeople.mapping.app.web.TaskServlet.ingestFile(TaskServlet.java:388)
    at org.waterforpeople.mapping.app.web.TaskServlet.handleRequest(TaskServlet.java:354)
    at com.gallatinsystems.framework.rest.AbstractRestApiServlet.executeRequest(AbstractRestApiServlet.java:85)
    at com.gallatinsystems.framework.rest.AbstractRestApiServlet.doPost(AbstractRestApiServlet.java:61) 

which is even stranger. Either the locations set contains a null object, or an object that has no key.

**Comment by stellanl** [comment]
Any thoughts on the second NPE, @muloem ?

**Comment by muloem** [comment]
@stellanl the second one seems connected to processing the answers attached to a SurveyInstance for the first time that contain a GEO question.  They do not have key yet so it fails.

**Comment by janagombitova** [comment]
Hi both, @stellanl and @muloem is there a way to test this fix? Is yes, can you please write the test plan for me? Thanks
