### ISSUE TITLE
Deletions fail because of 'transient instances'

### ISSUE THREAD

**Issue by stellanl** [akvo/akvo-flow#2116]
The problem in #857 is still around. In the log for akvoflow-149:

```2017-05-27 BST
14:03:56.877
org.waterforpeople.mapping.app.web.SurveyTaskServlet handleRequest: action: deleteQuestion id: 2440145 (SurveyTaskServlet.java:73)
14:03:57.515
com.gallatinsystems.framework.rest.AbstractRestApiServlet executeRequest: Could not execute rest request (AbstractRestApiServlet.java:95)
javax.jdo.JDOUserException: Transient instances cant be deleted.
	at org.datanucleus.jdo.NucleusJDOHelper.getJDOExceptionForNucleusException(NucleusJDOHelper.java:375)
	at org.datanucleus.jdo.JDOPersistenceManager.jdoDeletePersistent(JDOPersistenceManager.java:759)
	at org.datanucleus.jdo.JDOPersistenceManager.deletePersistent(JDOPersistenceManager.java:772)
	at com.gallatinsystems.framework.dao.BaseDAO.delete(BaseDAO.java:566)
	at com.gallatinsystems.survey.dao.QuestionDao.delete(QuestionDao.java:165)
	at com.gallatinsystems.survey.dao.QuestionDao.delete(QuestionDao.java:127)
	at org.waterforpeople.mapping.app.web.SurveyTaskServlet.handleRequest(SurveyTaskServlet.java:92)
	at com.gallatinsystems.framework.rest.AbstractRestApiServlet.executeRequest(AbstractRestApiServlet.java:85)
	at com.gallatinsystems.framework.rest.AbstractRestApiServlet.doPost(AbstractRestApiServlet.java:61)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:637)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
	at com.gallatinsystems.framework.servlet.PersistenceFilter.doFilter(PersistenceFilter.java:71)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:118)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:84)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:113)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:103)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:113)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:54)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:45)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.waterforpeople.mapping.app.web.rest.security.GaeAuthenticationFilter.doFilter(GaeAuthenticationFilter.java:92)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:105)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:87)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:192)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:160)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:259)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.apphosting.utils.servlet.ParseBlobUploadFilter.doFilter(ParseBlobUploadFilter.java:125)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.apphosting.runtime.jetty.SaveSessionFilter.doFilter(SaveSessionFilter.java:37)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.apphosting.utils.servlet.JdbcMySqlConnectionCleanupFilter.doFilter(JdbcMySqlConnectionCleanupFilter.java:60)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.apphosting.utils.servlet.TransactionCleanupFilter.doFilter(TransactionCleanupFilter.java:48)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
	at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
	at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
	at com.google.apphosting.runtime.jetty.AppVersionHandlerMap.handle(AppVersionHandlerMap.java:257)
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
	at org.mortbay.jetty.Server.handle(Server.java:326)
	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
	at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:923)
	at com.google.apphosting.runtime.jetty.RpcRequestParser.parseAvailable(RpcRequestParser.java:76)
	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
	at com.google.apphosting.runtime.jetty.JettyServletEngineAdapter.serviceRequest(JettyServletEngineAdapter.java:145)
	at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.dispatchServletRequest(JavaRuntime.java:644)
	at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.dispatchRequest(JavaRuntime.java:604)
	at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.run(JavaRuntime.java:574)
	at com.google.tracing.TraceContext$TraceContextRunnable.runInContext(TraceContext.java:453)
	at com.google.tracing.TraceContext$TraceContextRunnable$1.run(TraceContext.java:460)
	at com.google.tracing.CurrentContext.runInContext(CurrentContext.java:293)
	at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContextNoUnref(TraceContext.java:319)
	at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContext(TraceContext.java:311)
	at com.google.tracing.TraceContext$TraceContextRunnable.run(TraceContext.java:457)```

**Comment by stellanl** [comment]
Reading http://www.datanucleus.org:15080/products/accessplatform/jdo/persistence.html#lifecycle
I find that this error means that the object has not been persisted. That might mean that we either have a bogus id or that it has not been persisted _yet_, from some other thread.
If there is a race condition here, we might persist it shortly afterwards, which would explain all the orphan entities in the dbs.

**Comment by stellanl** [comment]
It's all about the caching. When an entity is retrieved from the cache, the connection to the datastore is lost. jdoStateManager member is null. So questions are never deleted from the datastore.

**Comment by stellanl** [comment]
Hmm, now I get ```javax.jdo.JDOUserException: Cannot read fields from a deleted object
     [java] FailedObject:com.google.appengine.api.datastore.Key:Question(6461829836439552)
     [java] 	at org.datanucleus.jdo.state.PersistentDeleted.transitionReadField(PersistentDeleted.java:115)
     [java] 	at org.datanucleus.state.AbstractStateManager.transitionReadField(AbstractStateManager.java:561)
     [java] 	at org.datanucleus.state.JDOStateManagerImpl.isLoaded(JDOStateManagerImpl.java:1900)
     [java] 	at com.gallatinsystems.survey.domain.Question.jdoGetorder(Question.java)
     [java] 	at com.gallatinsystems.survey.domain.Question.getOrder(Question.java:267)
     [java] 	at com.gallatinsystems.survey.dao.QuestionDao.listQuestionsByQuestionGroup(QuestionDao.java:649)
     [java] 	at com.gallatinsystems.survey.dao.QuestionDao.listQuestionsByQuestionGroup(QuestionDao.java:609)
     [java] 	at com.gallatinsystems.survey.dao.QuestionDao.delete(QuestionDao.java:173)
     [java] 	at com.gallatinsystems.survey.dao.QuestionDao.delete(QuestionDao.java:127)
     [java] 	at org.waterforpeople.mapping.app.web.SurveyTaskServlet.handleRequest(SurveyTaskServlet.java:92)
     [java] 	at com.gallatinsystems.framework.rest.AbstractRestApiServlet.executeRequest(AbstractRestApiServlet.java:85)
     [java] 	at com.gallatinsystems.framework.rest.AbstractRestApiServlet.doPost(AbstractRestApiServlet.java:61)
     [java] 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:637)
     [java] 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
     [java] 	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
```
So maybe the deleted Q is somehow listed in the group that we are now trying to reorder?

**Comment by stellanl** [comment]
Test plan:
Make three questions in a question group.
Delete the middle one. The last one should be renumbered.
Look in the GAE logs. There should be no errors for the POST /app_worker/surveytask call.

**Comment by stellanl** [comment]
I took another look at this. The first background deletion fails, the second (the deletequeue retries after 10s) succeeds. Setting the queue to delay by 1s, 10s and 20s, did not change this.

**Comment by stellanl** [comment]
The reason the deletion is done in the background is that it can take a long time to delete all the options etc inside it. ISTR it could hit the 1-minute limit...

**Comment by muloem** [comment]
Exactly. But I am wondering whether we can't do that already either in a frontend instance or in the frontend. So batch the delete actions together and fire them off from the frontend.  The reason for the delay in the backend is that we have to retrieve things first and then delete. But in the frontend we already know IDs and all info necessary to send  DELETE request straight away

**Comment by stellanl** [comment]
Do we know them all? All the translations for all the options?
