### ISSUE TITLE
Raw data reports import fails silently on error cells.

### ISSUE THREAD

**Issue by muloem** [akvo/akvo-flow#2192]
When importing a raw data spreadsheet, incase one of the cells has an error value, the entire report import throws an exception and silently fails without giving any warning as to what was the cause of the error.

The exception captured in the log files is

```
2017-07-12 00:03:02,603 [QuartziteScheduler_Worker-4] ERROR org.waterforpeople.mapping.dataexport.RawDataSpreadsheetImporter - Failed to import raw data report
java.lang.RuntimeException: Unexpected celltype (5)
	at org.apache.poi.ss.usermodel.DataFormatter.formatCellValue(DataFormatter.java:769)
	at org.apache.poi.ss.usermodel.DataFormatter.formatCellValue(DataFormatter.java:720)
	at org.waterforpeople.mapping.dataexport.ExportImportUtils.parseCellAsString(ExportImportUtils.java:69)
	at org.waterforpeople.mapping.dataexport.RawDataSpreadsheetImporter.parseInstance(RawDataSpreadsheetImporter.java:505)
	at org.waterforpeople.mapping.dataexport.RawDataSpreadsheetImporter.parseSheet(RawDataSpreadsheetImporter.java:212)
	at org.waterforpeople.mapping.dataexport.RawDataSpreadsheetImporter.executeImport(RawDataSpreadsheetImporter.java:131)
	at akvo.flow_services.uploader$raw_data.invoke(uploader.clj:168)
	at akvo.flow_services.uploader$bulk_upload.invoke(uploader.clj:259)
	at akvo.flow_services.scheduler.BulkUploadJob.execute(scheduler.clj:73)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:557)
```
The cell type mentioned is an error cell http://poi.apache.org/apidocs/org/apache/poi/ss/usermodel/Cell.html#CELL_TYPE_ERROR

Since a number of elements are processed in the report, we need to consider skipping the error cells or the row with error cells but then go ahead and process the rest of the data.  At the end we could give a summary report stating how data was processed.

**Comment by janagombitova** [comment]
https://akvoo.reamaze.com/admin/conversations/smart-seeds-raw-data-upload-error issue experienced here. Import failed on a few cells holding this value: #DIV/0!

A simple solution for now, can be to fail the import but inform the user by pointing to where the error cell is/are.

**Comment by janagombitova** [comment]
Created via Reamaze:

Link: https://akvoo.reamaze.com/admin/conversations/smart-seeds-raw-data-upload-error
