### ISSUE TITLE
Avoid concurrent modification errors

### ISSUE THREAD

**Issue by stellanl** [akvo/akvo-flow#2931]
We get a lot of Concurrent Modification errors for the updates of SurveyQuestionSummary data.
All are executed on default task queue, but the surveyResponseCount queue is the only queue that allows only one task at a time, and is clearly intended to be used for this.

**Comment by stellanl** [comment]
Turns out this data is used for the Data->Charts feature, so cannot be removed without removing that.
We should instead run the update on a special task queue to guard against concurrent modificaiton errors.

**Comment by stellanl** [comment]
Part of the stack dump:
    at com.gallatinsystems.framework.dao.BaseDAO.save(BaseDAO.java:147)
    at org.waterforpeople.mapping.analytics.dao.SurveyQuestionSummaryDao.save(SurveyQuestionSummaryDao.java:237)
    at org.waterforpeople.mapping.domain.SurveyInstance.updateSummaryCounts(SurveyInstance.java:329)
    at org.waterforpeople.mapping.dao.SurveyInstanceDAO.save(SurveyInstanceDAO.java:161)
    at org.waterforpeople.mapping.app.web.TaskServlet.processFile(TaskServlet.java:201)
    at org.waterforpeople.mapping.app.web.TaskServlet.ingestFile(TaskServlet.java:361)

**Comment by stellanl** [comment]
Test plan:
1. Submit answers for a form with an option question
2. Check the logs for any "concurrent modification" errors. There should be none.
