### ISSUE TITLE
Update gcloud SDK + App Engine SDK

### ISSUE THREAD

**Issue by iperdomo** [akvo/akvo-flow#3346]
NPE when starting local dev server
```
akvo-flow_1           | [INFO] GCLOUD: 2019-12-10 05:46:14.219:INFO::main: Logging initialized @1117ms
akvo-flow_1           | [INFO] GCLOUD: 2019-12-10 05:46:15.126:INFO:oejs.Server:main: jetty-9.3.18.v20170406
akvo-flow_1           | [INFO] GCLOUD: 2019-12-10 05:46:15.970:WARN:oeja.ClassInheritanceHandler:qtp283383329-17: 
akvo-flow_1           | [INFO] GCLOUD: java.lang.NullPointerException
akvo-flow_1           | [INFO] GCLOUD: 	at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936)
akvo-flow_1           | [INFO] GCLOUD: 	at org.eclipse.jetty.annotations.ClassInheritanceHandler.addToInheritanceMap(ClassInheritanceHandler.java:72)
akvo-flow_1           | [INFO] GCLOUD: 	at org.eclipse.jetty.annotations.ClassInheritanceHandler.handle(ClassInheritanceHandler.java:58)
akvo-flow_1           | [INFO] GCLOUD: 	at org.eclipse.jetty.annotations.AnnotationParser$MyClassVisitor.visit(AnnotationParser.java:476)
akvo-flow_1           | [INFO] GCLOUD: 	at org.objectweb.asm.ClassReader.accept(ClassReader.java:650)
akvo-flow_1           | [INFO] GCLOUD: 	at org.objectweb.asm.ClassReader.accept(ClassReader.java:525)
akvo-flow_1           | [INFO] GCLOUD: 	at org.eclipse.jetty.annotations.AnnotationParser.scanClass(AnnotationParser.java:978)
akvo-flow_1           | [INFO] GCLOUD: 	at org.eclipse.jetty.annotations.AnnotationParser.parseJarEntry(AnnotationParser.java:958)
akvo-flow_1           | [INFO] GCLOUD: 	at org.eclipse.jetty.annotations.AnnotationParser.parseJar(AnnotationParser.java:902)
akvo-flow_1           | [INFO] GCLOUD: 	at org.eclipse.jetty.annotations.AnnotationParser.parse(AnnotationParser.java:851)
akvo-flow_1           | [INFO] GCLOUD: 	at org.eclipse.jetty.annotations.AnnotationConfiguration$ParserTask.call(AnnotationConfiguration.java:163)
akvo-flow_1           | [INFO] GCLOUD: 	at org.eclipse.jetty.annotations.AnnotationConfiguration$1.run(AnnotationConfiguration.java:546)
akvo-flow_1           | [INFO] GCLOUD: 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
akvo-flow_1           | [INFO] GCLOUD: 	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
akvo-flow_1           | [INFO] GCLOUD: 	at java.lang.Thread.run(Thread.java:748)
akvo-flow_1           | [INFO] GCLOUD: 2019-12-10 05:46:16.863:WARN:oeja.ClassInheritanceHandler:qtp283383329-21: 
[...]
```

**Comment by iperdomo** [comment]
Updating to new SDK shows now lots of warnings. 
See:
* https://github.com/cloudendpoints/endpoints-java/issues/174
* https://github.com/eclipse/jetty.project/issues/3190

Attached the full log:
[flow.log](https://github.com/akvo/akvo-flow/files/3943279/flow.log)

**Comment by iperdomo** [comment]
```
 docker-compose exec akvo-flow bash -c 'cd /app/src/GAE && /app/src/ci/run-as-user.sh mvn dependency:tree -Dverbose=true'
```
Output:
```
[INFO] Scanning for projects...
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Building akvo-flow 1
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ akvo-flow ---
[INFO] org.akvo.flow:akvo-flow:war:1
[INFO] +- com.google.appengine:appengine-api-1.0-sdk:jar:1.9.77:compile
[INFO] +- jstl:jstl:jar:1.2:compile
[INFO] +- net.sf.jsr107cache:jsr107cache:jar:1.1:compile
[INFO] +- javax.jdo:jdo-api:jar:3.1:compile
[INFO] |  \- javax.transaction:transaction-api:jar:1.1:compile
[INFO] +- com.google.appengine.orm:datanucleus-appengine:jar:2.1.2:compile
[INFO] |  +- (com.google.appengine:appengine-api-1.0-sdk:jar:1.7.5:compile - omitted for conflict with 1.9.77)
[INFO] |  +- (org.datanucleus:datanucleus-core:jar:3.1.3:compile - omitted for duplicate)
[INFO] |  +- org.datanucleus:datanucleus-enhancer:jar:3.1.1:compile
[INFO] |  |  \- org.ow2.asm:asm:jar:4.0:compile
[INFO] |  \- (javax.jdo:jdo-api:jar:3.0.1:compile - omitted for conflict with 3.1)
[INFO] +- org.datanucleus:datanucleus-core:jar:3.1.3:compile
[INFO] +- org.datanucleus:datanucleus-api-jdo:jar:3.1.3:compile
[INFO] +- org.apache.velocity:velocity:jar:1.6.2:compile
[INFO] |  +- commons-collections:commons-collections:jar:3.2.1:compile
[INFO] |  +- (commons-lang:commons-lang:jar:2.4:compile - omitted for duplicate)
[INFO] |  \- oro:oro:jar:2.0.8:compile
[INFO] +- org.springframework:spring-web:jar:4.3.23.RELEASE:compile
[INFO] |  +- (org.springframework:spring-aop:jar:4.3.23.RELEASE:compile - omitted for duplicate)
[INFO] |  +- (org.springframework:spring-beans:jar:4.3.23.RELEASE:compile - omitted for duplicate)
[INFO] |  +- (org.springframework:spring-context:jar:4.3.23.RELEASE:compile - omitted for duplicate)
[INFO] |  \- (org.springframework:spring-core:jar:4.3.23.RELEASE:compile - omitted for duplicate)
[INFO] +- org.springframework:spring-context:jar:4.3.23.RELEASE:compile
[INFO] |  +- (org.springframework:spring-aop:jar:4.3.23.RELEASE:compile - omitted for duplicate)
[INFO] |  +- (org.springframework:spring-beans:jar:4.3.23.RELEASE:compile - omitted for duplicate)
[INFO] |  +- (org.springframework:spring-core:jar:4.3.23.RELEASE:compile - omitted for duplicate)
[INFO] |  \- (org.springframework:spring-expression:jar:4.3.23.RELEASE:compile - omitted for duplicate)
[INFO] +- org.springframework:spring-beans:jar:4.3.23.RELEASE:compile
[INFO] |  \- (org.springframework:spring-core:jar:4.3.23.RELEASE:compile - omitted for duplicate)
[INFO] +- org.springframework:spring-core:jar:4.3.23.RELEASE:compile
[INFO] |  \- commons-logging:commons-logging:jar:1.2:compile
[INFO] +- org.springframework:spring-aop:jar:4.3.23.RELEASE:compile
[INFO] |  +- (org.springframework:spring-beans:jar:4.3.23.RELEASE:compile - omitted for duplicate)
[INFO] |  \- (org.springframework:spring-core:jar:4.3.23.RELEASE:compile - omitted for duplicate)
[INFO] +- org.springframework:spring-context-support:jar:4.3.23.RELEASE:compile
[INFO] |  +- (org.springframework:spring-beans:jar:4.3.23.RELEASE:compile - omitted for duplicate)
[INFO] |  +- (org.springframework:spring-context:jar:4.3.23.RELEASE:compile - omitted for duplicate)
[INFO] |  \- (org.springframework:spring-core:jar:4.3.23.RELEASE:compile - omitted for duplicate)
[INFO] +- org.springframework:spring-expression:jar:4.3.23.RELEASE:compile
[INFO] |  \- (org.springframework:spring-core:jar:4.3.23.RELEASE:compile - omitted for duplicate)
[INFO] +- org.springframework:spring-webmvc:jar:4.3.23.RELEASE:compile
[INFO] |  +- (org.springframework:spring-aop:jar:4.3.23.RELEASE:compile - omitted for duplicate)
[INFO] |  +- (org.springframework:spring-beans:jar:4.3.23.RELEASE:compile - omitted for duplicate)
[INFO] |  +- (org.springframework:spring-context:jar:4.3.23.RELEASE:compile - omitted for duplicate)
[INFO] |  +- (org.springframework:spring-core:jar:4.3.23.RELEASE:compile - omitted for duplicate)
[INFO] |  +- (org.springframework:spring-expression:jar:4.3.23.RELEASE:compile - omitted for duplicate)
[INFO] |  \- (org.springframework:spring-web:jar:4.3.23.RELEASE:compile - omitted for duplicate)
[INFO] +- org.json:json:jar:20090211:compile
[INFO] +- org.apache.poi:poi:jar:3.8:compile
[INFO] |  \- commons-codec:commons-codec:jar:1.5:compile
[INFO] +- org.springframework.security:spring-security-core:jar:4.2.12.RELEASE:compile
[INFO] |  +- aopalliance:aopalliance:jar:1.0:compile
[INFO] |  +- (org.springframework:spring-aop:jar:4.3.23.RELEASE:compile - omitted for duplicate)
[INFO] |  +- (org.springframework:spring-beans:jar:4.3.23.RELEASE:compile - omitted for duplicate)
[INFO] |  +- (org.springframework:spring-context:jar:4.3.23.RELEASE:compile - omitted for duplicate)
[INFO] |  +- (org.springframework:spring-core:jar:4.3.23.RELEASE:compile - omitted for duplicate)
[INFO] |  \- (org.springframework:spring-expression:jar:4.3.23.RELEASE:compile - omitted for duplicate)
[INFO] +- org.springframework.security:spring-security-web:jar:4.2.12.RELEASE:compile
[INFO] |  +- (aopalliance:aopalliance:jar:1.0:compile - omitted for duplicate)
[INFO] |  +- (org.springframework.security:spring-security-core:jar:4.2.12.RELEASE:compile - omitted for duplicate)
[INFO] |  +- (org.springframework:spring-beans:jar:4.3.23.RELEASE:compile - omitted for duplicate)
[INFO] |  +- (org.springframework:spring-context:jar:4.3.23.RELEASE:compile - omitted for duplicate)
[INFO] |  +- (org.springframework:spring-core:jar:4.3.23.RELEASE:compile - omitted for duplicate)
[INFO] |  +- (org.springframework:spring-expression:jar:4.3.23.RELEASE:compile - omitted for duplicate)
[INFO] |  \- (org.springframework:spring-web:jar:4.3.23.RELEASE:compile - omitted for duplicate)
[INFO] +- org.springframework.security:spring-security-config:jar:4.2.12.RELEASE:compile
[INFO] |  +- (aopalliance:aopalliance:jar:1.0:compile - omitted for duplicate)
[INFO] |  +- (org.springframework.security:spring-security-core:jar:4.2.12.RELEASE:compile - omitted for duplicate)
[INFO] |  +- (org.springframework:spring-aop:jar:4.3.23.RELEASE:compile - omitted for duplicate)
[INFO] |  +- (org.springframework:spring-beans:jar:4.3.23.RELEASE:compile - omitted for duplicate)
[INFO] |  +- (org.springframework:spring-context:jar:4.3.23.RELEASE:compile - omitted for duplicate)
[INFO] |  \- (org.springframework:spring-core:jar:4.3.23.RELEASE:compile - omitted for duplicate)
[INFO] +- com.fasterxml.jackson.core:jackson-core:jar:2.10.0:compile
[INFO] +- com.fasterxml.jackson.core:jackson-databind:jar:2.10.0:compile
[INFO] |  +- (com.fasterxml.jackson.core:jackson-annotations:jar:2.10.0:compile - omitted for duplicate)
[INFO] |  \- (com.fasterxml.jackson.core:jackson-core:jar:2.10.0:compile - omitted for duplicate)
[INFO] +- com.fasterxml.jackson.core:jackson-annotations:jar:2.10.0:compile
[INFO] +- com.fasterxml.jackson.dataformat:jackson-dataformat-xml:jar:2.10.0:compile
[INFO] |  +- (com.fasterxml.jackson.core:jackson-core:jar:2.10.0:compile - omitted for duplicate)
[INFO] |  +- (com.fasterxml.jackson.core:jackson-annotations:jar:2.10.0:compile - omitted for duplicate)
[INFO] |  +- (com.fasterxml.jackson.core:jackson-databind:jar:2.10.0:compile - omitted for duplicate)
[INFO] |  +- com.fasterxml.jackson.module:jackson-module-jaxb-annotations:jar:2.10.0:compile
[INFO] |  |  +- (com.fasterxml.jackson.core:jackson-annotations:jar:2.10.0:compile - omitted for duplicate)
[INFO] |  |  +- (com.fasterxml.jackson.core:jackson-core:jar:2.10.0:compile - omitted for duplicate)
[INFO] |  |  +- (com.fasterxml.jackson.core:jackson-databind:jar:2.10.0:compile - omitted for duplicate)
[INFO] |  |  +- jakarta.xml.bind:jakarta.xml.bind-api:jar:2.3.2:compile
[INFO] |  |  |  \- (jakarta.activation:jakarta.activation-api:jar:1.2.1:compile - omitted for duplicate)
[INFO] |  |  \- jakarta.activation:jakarta.activation-api:jar:1.2.1:compile
[INFO] |  +- org.codehaus.woodstox:stax2-api:jar:4.2:compile
[INFO] |  \- com.fasterxml.woodstox:woodstox-core:jar:6.0.1:compile
[INFO] |     \- (org.codehaus.woodstox:stax2-api:jar:4.2:compile - omitted for duplicate)
[INFO] +- com.google.appengine:appengine-jsr107cache:jar:1.9.77:compile
[INFO] +- com.google.appengine:appengine-endpoints:jar:1.9.77:compile
[INFO] |  \- (com.google.appengine:appengine-api-1.0-sdk:jar:1.9.77:compile - omitted for duplicate)
[INFO] +- org.apache.poi:poi-ooxml:jar:3.8:compile
[INFO] |  +- (org.apache.poi:poi:jar:3.8:compile - omitted for duplicate)
[INFO] |  +- org.apache.poi:poi-ooxml-schemas:jar:3.8:compile
[INFO] |  |  \- org.apache.xmlbeans:xmlbeans:jar:2.3.0:compile
[INFO] |  |     \- stax:stax-api:jar:1.0.1:compile
[INFO] |  \- dom4j:dom4j:jar:1.6.1:compile
[INFO] |     \- (xml-apis:xml-apis:jar:1.0.b2:compile - omitted for conflict with 1.3.04)
[INFO] +- commons-beanutils:commons-beanutils:jar:1.8.3:compile
[INFO] |  \- (commons-logging:commons-logging:jar:1.1.1:compile - omitted for conflict with 1.2)
[INFO] +- commons-io:commons-io:jar:2.4:runtime
[INFO] +- commons-lang:commons-lang:jar:2.4:compile
[INFO] +- org.junit.jupiter:junit-jupiter-api:jar:5.4.0:test
[INFO] |  +- org.apiguardian:apiguardian-api:jar:1.0.0:test
[INFO] |  +- org.opentest4j:opentest4j:jar:1.1.1:test
[INFO] |  \- org.junit.platform:junit-platform-commons:jar:1.4.0:test
[INFO] |     \- (org.apiguardian:apiguardian-api:jar:1.0.0:test - omitted for duplicate)
[INFO] +- org.junit.jupiter:junit-jupiter-engine:jar:5.4.0:test
[INFO] |  +- (org.apiguardian:apiguardian-api:jar:1.0.0:test - omitted for duplicate)
[INFO] |  +- org.junit.platform:junit-platform-engine:jar:1.4.0:test
[INFO] |  |  +- (org.apiguardian:apiguardian-api:jar:1.0.0:test - omitted for duplicate)
[INFO] |  |  +- (org.opentest4j:opentest4j:jar:1.1.1:test - omitted for duplicate)
[INFO] |  |  \- (org.junit.platform:junit-platform-commons:jar:1.4.0:test - omitted for duplicate)
[INFO] |  \- (org.junit.jupiter:junit-jupiter-api:jar:5.4.0:test - omitted for duplicate)
[INFO] +- com.google.appengine:appengine-testing:jar:1.9.77:test
[INFO] +- com.google.appengine:appengine-api-stubs:jar:1.9.77:test
[INFO] +- com.google.appengine:appengine-tools-sdk:jar:1.9.77:test
[INFO] +- com.google.api-client:google-api-client-appengine:jar:1.23.0:test
[INFO] |  +- com.google.oauth-client:google-oauth-client-appengine:jar:1.23.0:test
[INFO] |  |  +- (com.google.http-client:google-http-client-appengine:jar:1.23.0:test - omitted for duplicate)
[INFO] |  |  +- com.google.oauth-client:google-oauth-client:jar:1.23.0:test
[INFO] |  |  |  +- (com.google.http-client:google-http-client:jar:1.23.0:test - omitted for duplicate)
[INFO] |  |  |  \- (com.google.code.findbugs:jsr305:jar:1.3.9:test - omitted for conflict with 3.0.2)
[INFO] |  |  \- com.google.oauth-client:google-oauth-client-servlet:jar:1.23.0:test
[INFO] |  |     +- (com.google.oauth-client:google-oauth-client:jar:1.23.0:test - omitted for duplicate)
[INFO] |  |     +- com.google.http-client:google-http-client-jdo:jar:1.23.0:test
[INFO] |  |     |  +- (com.google.http-client:google-http-client:jar:1.23.0:test - omitted for duplicate)
[INFO] |  |     |  \- (javax.jdo:jdo2-api:jar:2.3-eb:test - omitted for duplicate)
[INFO] |  |     \- (javax.jdo:jdo2-api:jar:2.3-eb:test - omitted for duplicate)
[INFO] |  +- com.google.api-client:google-api-client:jar:1.23.0:test
[INFO] |  |  +- (com.google.oauth-client:google-oauth-client:jar:1.23.0:test - omitted for duplicate)
[INFO] |  |  +- com.google.http-client:google-http-client-jackson2:jar:1.23.0:test
[INFO] |  |  |  +- (com.google.http-client:google-http-client:jar:1.23.0:test - omitted for duplicate)
[INFO] |  |  |  \- (com.fasterxml.jackson.core:jackson-core:jar:2.1.3:test - omitted for conflict with 2.10.0)
[INFO] |  |  \- com.google.guava:guava-jdk5:jar:17.0:test
[INFO] |  +- com.google.api-client:google-api-client-servlet:jar:1.23.0:test
[INFO] |  |  +- (com.google.oauth-client:google-oauth-client-servlet:jar:1.23.0:test - omitted for duplicate)
[INFO] |  |  +- (com.google.api-client:google-api-client:jar:1.23.0:test - omitted for duplicate)
[INFO] |  |  +- javax.servlet:servlet-api:jar:2.5:test
[INFO] |  |  \- (javax.jdo:jdo2-api:jar:2.3-eb:test - omitted for conflict with 2.3-20090302111651)
[INFO] |  \- com.google.http-client:google-http-client-appengine:jar:1.23.0:test
[INFO] |     \- com.google.http-client:google-http-client:jar:1.23.0:test
[INFO] |        +- (com.google.code.findbugs:jsr305:jar:1.3.9:test - omitted for duplicate)
[INFO] |        \- org.apache.httpcomponents:httpclient:jar:4.0.1:test
[INFO] |           +- org.apache.httpcomponents:httpcore:jar:4.0.1:test
[INFO] |           +- (commons-logging:commons-logging:jar:1.1.1:test - omitted for conflict with 1.2)
[INFO] |           \- (commons-codec:commons-codec:jar:1.3:test - omitted for conflict with 1.5)
[INFO] +- org.jfree:jfreechart:jar:1.0.14:compile
[INFO] |  +- org.jfree:jcommon:jar:1.0.17:compile
[INFO] |  +- xml-apis:xml-apis:jar:1.3.04:compile
[INFO] |  \- com.lowagie:itext:jar:2.1.5:compile
[INFO] |     +- bouncycastle:bcmail-jdk14:jar:138:compile
[INFO] |     \- bouncycastle:bcprov-jdk14:jar:138:compile
[INFO] +- com.auth0:jwks-rsa:jar:0.8.2:compile
[INFO] |  +- (commons-codec:commons-codec:jar:1.12:runtime - omitted for conflict with 1.5)
[INFO] |  +- (commons-io:commons-io:jar:2.6:runtime - omitted for conflict with 2.4)
[INFO] |  +- (com.fasterxml.jackson.core:jackson-databind:jar:2.9.9:runtime - omitted for conflict with 2.10.0)
[INFO] |  \- com.google.guava:guava:jar:27.1-jre:runtime
[INFO] |     +- com.google.guava:failureaccess:jar:1.0.1:runtime
[INFO] |     +- com.google.guava:listenablefuture:jar:9999.0-empty-to-avoid-conflict-with-guava:runtime
[INFO] |     +- com.google.code.findbugs:jsr305:jar:3.0.2:runtime
[INFO] |     +- org.checkerframework:checker-qual:jar:2.5.2:runtime
[INFO] |     +- com.google.errorprone:error_prone_annotations:jar:2.2.0:runtime
[INFO] |     +- com.google.j2objc:j2objc-annotations:jar:1.1:runtime
[INFO] |     \- org.codehaus.mojo:animal-sniffer-annotations:jar:1.17:runtime
[INFO] +- com.auth0:mvc-auth-commons:jar:1.0.8:compile
[INFO] |  +- com.auth0:auth0:jar:1.13.3:compile
[INFO] |  |  +- com.squareup.okhttp3:okhttp:jar:3.9.1:runtime
[INFO] |  |  |  \- com.squareup.okio:okio:jar:1.13.0:runtime
[INFO] |  |  +- com.squareup.okhttp3:logging-interceptor:jar:3.9.1:runtime
[INFO] |  |  |  \- (com.squareup.okhttp3:okhttp:jar:3.9.1:runtime - omitted for duplicate)
[INFO] |  |  +- (com.fasterxml.jackson.core:jackson-databind:jar:2.9.9:runtime - omitted for conflict with 2.10.0)
[INFO] |  |  \- (commons-codec:commons-codec:jar:1.11:runtime - omitted for conflict with 1.5)
[INFO] |  +- com.auth0:java-jwt:jar:3.8.1:compile
[INFO] |  |  +- (com.fasterxml.jackson.core:jackson-databind:jar:2.9.9:runtime - omitted for conflict with 2.10.0)
[INFO] |  |  \- (commons-codec:commons-codec:jar:1.12:runtime - omitted for conflict with 1.5)
[INFO] |  +- (com.auth0:jwks-rsa:jar:0.8.2:compile - omitted for duplicate)
[INFO] |  +- javax.servlet:javax.servlet-api:jar:3.1.0:runtime
[INFO] |  +- org.bouncycastle:bcprov-jdk15on:jar:1.61:runtime
[INFO] |  \- org.apache.commons:commons-lang3:jar:3.9:runtime
[INFO] +- com.beoui:geocell:jar:0.0.10.1:compile
[INFO] |  +- log4j:log4j:jar:1.2.16:compile
[INFO] |  +- (commons-lang:commons-lang:jar:2.4:compile - omitted for duplicate)
[INFO] |  +- javax.jdo:jdo2-api:jar:2.3-20090302111651:compile
[INFO] |  \- org.apache.geronimo.specs:geronimo-jpa_3.0_spec:jar:1.1.1:compile
[INFO] +- com.vividsolutions:jts:jar:1.13:compile
[INFO] \- com.google.gwt:gwt-dev:jar:2.5.1:provided
[INFO]    \- (org.json:json:jar:20090211:provided - omitted for duplicate)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.759 s
[INFO] Finished at: 2019-12-10T06:11:20Z
[INFO] Final Memory: 16M/483M
[INFO] ------------------------------------------------------------------------
```
