### ISSUE TITLE
Index needed for datastore query

### ISSUE THREAD

**Issue by muloem** [akvo/akvo-flow#3368]
An exception about a missing datastore index is logged when the extractGeoTag cron job is executed.

```com.google.appengine.api.datastore.DatastoreNeedIndexException: no matching index found. recommended index is:
- kind: QuestionAnswerStore
  properties:
  - name: type
  - name: lastUpdateDateTime

The suggested index for this query is:
    <datastore-index kind="QuestionAnswerStore" ancestor="false" source="manual">
        <property name="type" direction="asc"/>
        <property name="lastUpdateDateTime" direction="asc"/>
    </datastore-index>


	at com.google.appengine.api.datastore.DatastoreApiHelper.translateError(DatastoreApiHelper.java:55)
	at com.google.appengine.api.datastore.DatastoreApiHelper$1.convertException(DatastoreApiHelper.java:127)
	at com.google.appengine.api.utils.FutureWrapper.get(FutureWrapper.java:97)
	at com.google.appengine.api.utils.FutureWrapper.get(FutureWrapper.java:89)
	at com.google.appengine.api.datastore.FutureHelper.getInternal(FutureHelper.java:68)
	at com.google.appengine.api.datastore.FutureHelper.quietGet(FutureHelper.java:32)
	at com.google.appengine.api.datastore.BaseQueryResultsSource.getIndexList(BaseQueryResultsSource.java:154)
	at com.google.appengine.api.datastore.BaseQueryResultsSource.loadMoreEntities(BaseQueryResultsSource.java:187)
	at com.google.appengine.api.datastore.QueryResultIteratorImpl.ensureLoaded(QueryResultIteratorImpl.java:160)
	at com.google.appengine.api.datastore.QueryResultIteratorImpl.nextList(QueryResultIteratorImpl.java:113)
	at com.google.appengine.api.datastore.LazyList.forceResolveToIndex(LazyList.java:84)
	at com.google.appengine.api.datastore.LazyList.getCursor(LazyList.java:284)
	at com.google.appengine.datanucleus.query.DatastoreQuery.performExecute(DatastoreQuery.java:334)
	at com.google.appengine.datanucleus.query.JDOQLQuery.performExecute(JDOQLQuery.java:164)
	at org.datanucleus.store.query.Query.executeQuery(Query.java:1789)
	at org.datanucleus.store.query.Query.executeWithMap(Query.java:1693)
	at org.datanucleus.api.jdo.JDOQuery.executeWithMap(JDOQuery.java:334)
	at org.waterforpeople.mapping.dao.QuestionAnswerStoreDao.listByTypeAndDate(QuestionAnswerStoreDao.java:114)
	at org.waterforpeople.mapping.app.web.CronCommanderServlet.extractImageFileGeotags(CronCommanderServlet.java:253)
	at org.waterforpeople.mapping.app.web.CronCommanderServlet.doGet(CronCommanderServlet.java:95)```

**Comment by stellanl** [comment]
Test plan:

1. From a browser, trigger the cron job by accessing: /cron/croncommander?action=extractImageFileGeotags
2. Check that no errors are logged.
