### ISSUE TITLE
Exceptions on extract geotag from images cron task

### ISSUE THREAD

**Issue by iperdomo** [akvo/akvo-flow#3442]
Checking the errors after deploying the version `20200219-102312` we found exceptions related to the cron task of extracting geo info from images, e.g.

````
com.google.apphosting.runtime.jetty9.JettyLogger warn: /cron/croncommander
com.google.apphosting.api.ApiProxy$CancelledException: The API call datastore_v3.Put() was cancelled because the overall HTTP request deadline was reached while waiting for concurrent API calls.
	at com.google.apphosting.runtime.ApiProxyImpl$2.get(ApiProxyImpl.java:458)
	at com.google.apphosting.runtime.ApiProxyImpl$2.get(ApiProxyImpl.java:455)
	at com.google.appengine.api.utils.FutureWrapper.get(FutureWrapper.java:89)
	at com.google.appengine.api.datastore.Batcher$ReorderingMultiFuture.get(Batcher.java:114)
	at com.google.appengine.api.utils.FutureWrapper.get(FutureWrapper.java:89)
	at com.google.appengine.api.utils.FutureWrapper.get(FutureWrapper.java:89)
	at com.google.appengine.api.datastore.FutureHelper.getInternal(FutureHelper.java:68)
	at com.google.appengine.api.datastore.FutureHelper.quietGet(FutureHelper.java:32)
	at com.google.appengine.api.datastore.DatastoreServiceImpl.put(DatastoreServiceImpl.java:56)
	at com.google.appengine.datanucleus.WrappedDatastoreService.put(WrappedDatastoreService.java:100)
	at com.google.appengine.datanucleus.EntityUtils.putEntitiesIntoDatastore(EntityUtils.java:759)
	at com.google.appengine.datanucleus.EntityUtils.putEntityIntoDatastore(EntityUtils.java:706)
	at com.google.appengine.datanucleus.DatastorePersistenceHandler.updateObject(DatastorePersistenceHandler.java:429)
	at org.datanucleus.state.JDOStateManager.flush(JDOStateManager.java:3841)
	at org.datanucleus.ObjectManagerImpl.flushInternalWithOrdering(ObjectManagerImpl.java:3888)
	at org.datanucleus.ObjectManagerImpl.flushInternal(ObjectManagerImpl.java:3811)
	at org.datanucleus.ObjectManagerImpl.processNontransactionalAtomicChanges(ObjectManagerImpl.java:1231)
	at org.datanucleus.ObjectManagerImpl.processNontransactionalUpdate(ObjectManagerImpl.java:1196)
	at org.datanucleus.state.AbstractStateManager.setObjectField(AbstractStateManager.java:2189)
	at com.gallatinsystems.framework.domain.BaseDomain.jdoSetlastUpdateDateTime(BaseDomain.java)
	at com.gallatinsystems.framework.domain.BaseDomain.setLastUpdateDateTime(BaseDomain.java:73)
	at com.gallatinsystems.framework.dao.BaseDAO.save(BaseDAO.java:117)
	at org.waterforpeople.mapping.dao.QuestionAnswerStoreDao.save(QuestionAnswerStoreDao.java:296)
	at org.waterforpeople.mapping.app.web.CronCommanderServlet.extractImageFileGeotags(CronCommanderServlet.java:303)
	at org.waterforpeople.mapping.app.web.CronCommanderServlet.doGet(CronCommanderServlet.java:95)
````
````
 com.google.apphosting.api.ApiProxy$CancelledException: The API call datastore_v3.Put() was cancelled because the overall HTTP request deadline was reached while waiting for concurrent API calls.

        at com.google.apphosting.runtime.ApiProxyImpl$2.get (ApiProxyImpl.java:458)
        at com.google.apphosting.runtime.ApiProxyImpl$2.get (ApiProxyImpl.java:455)
        at com.google.appengine.api.utils.FutureWrapper.get (FutureWrapper.java:89)
        at com.google.appengine.api.datastore.Batcher$ReorderingMultiFuture.get (Batcher.java:114)
        at com.google.appengine.api.utils.FutureWrapper.get (FutureWrapper.java:89)
        at com.google.appengine.api.utils.FutureWrapper.get (FutureWrapper.java:89)
        at com.google.appengine.api.datastore.FutureHelper.getInternal (FutureHelper.java:68)
        at com.google.appengine.api.datastore.FutureHelper.quietGet (FutureHelper.java:32)
        at com.google.appengine.api.datastore.DatastoreServiceImpl.put (DatastoreServiceImpl.java:56)
        at com.google.appengine.datanucleus.WrappedDatastoreService.put (WrappedDatastoreService.java:100)
        at com.google.appengine.datanucleus.EntityUtils.putEntitiesIntoDatastore (EntityUtils.java:759)
        at com.google.appengine.datanucleus.EntityUtils.putEntityIntoDatastore (EntityUtils.java:706)
        at com.google.appengine.datanucleus.DatastorePersistenceHandler.updateObject (DatastorePersistenceHandler.java:429)
        at org.datanucleus.state.JDOStateManager.flush (JDOStateManager.java:3841)
        at org.datanucleus.ObjectManagerImpl.flushInternalWithOrdering (ObjectManagerImpl.java:3888)
        at org.datanucleus.ObjectManagerImpl.flushInternal (ObjectManagerImpl.java:3811)
        at org.datanucleus.ObjectManagerImpl.processNontransactionalAtomicChanges (ObjectManagerImpl.java:1231)
        at org.datanucleus.ObjectManagerImpl.processNontransactionalUpdate (ObjectManagerImpl.java:1196)
        at org.datanucleus.state.AbstractStateManager.setObjectField (AbstractStateManager.java:2189)
        at com.gallatinsystems.framework.domain.BaseDomain.jdoSetlastUpdateDateTime (BaseDomain.java)
        at com.gallatinsystems.framework.domain.BaseDomain.setLastUpdateDateTime (BaseDomain.java:73)
        at com.gallatinsystems.framework.dao.BaseDAO.save (BaseDAO.java:117)
        at org.waterforpeople.mapping.dao.QuestionAnswerStoreDao.save (QuestionAnswerStoreDao.java:296)
        at org.waterforpeople.mapping.app.web.CronCommanderServlet.extractImageFileGeotags (CronCommanderServlet.java:303)
        at org.waterforpeople.mapping.app.web.CronCommanderServlet.doGet (CronCommanderServlet.java:95)

````

Suggestion:

* Not sure if just using a smaller batch size for the QAS query could solve the problem
* A more elaborated one: The cron can be the _trigger_ to call some `Task` that takes care of a _subset_ of the images, and then _continues_ with the rest of unprocessed images (via a cursor get parameter).

**Comment by stellanl** [comment]
This has appeared now, since the db index needed by this job was not deployed until recently; the jobs used to abort almost immediately without any processing.
When testing the data script version of it on uat-1, it runs in less than a minute, so something is very different. It finds 16432 IMAGE answers, 26 of which were modified in the last month. Processing 26 items cannot possibly take 600 seconds unless sth weird happens. Will add more logging and test on sandbox.

**Comment by iperdomo** [comment]
```
2020-03-22 15:30:04.046 CET
org.akvo.flow.events.EventLogger storeEvent: could not store answerUpdated event. Error: java.util.concurrent.CancellationException: Task was cancelled. (EventLogger.java:130)
java.util.concurrent.CancellationException: Task was cancelled.
	at com.google.common.util.concurrent.AbstractFuture.cancellationExceptionWithCause(AbstractFuture.java:1389)
	at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:565)
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:446)
	at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:109)
	at com.google.appengine.tools.development.TimedFuture.get(TimedFuture.java:42)
	at com.google.common.util.concurrent.ForwardingFuture.get(ForwardingFuture.java:62)
	at com.google.appengine.api.utils.FutureWrapper.get(FutureWrapper.java:89)
	at com.google.appengine.api.datastore.Batcher$ReorderingMultiFuture.get(Batcher.java:114)
	at com.google.appengine.api.utils.FutureWrapper.get(FutureWrapper.java:89)
	at com.google.appengine.api.utils.FutureWrapper.get(FutureWrapper.java:89)
	at com.google.appengine.api.datastore.FutureHelper.getInternal(FutureHelper.java:68)
	at com.google.appengine.api.datastore.FutureHelper.quietGet(FutureHelper.java:32)
	at com.google.appengine.api.datastore.DatastoreServiceImpl.put(DatastoreServiceImpl.java:56)
	at org.akvo.flow.events.EventLogger.storeEvent(EventLogger.java:127)
	at org.akvo.flow.events.EventLogger.logPut(EventLogger.java:181)
	at sun.reflect.GeneratedMethodAccessor16.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.appengine.api.datastore.DatastoreCallbacksImpl$1.run(DatastoreCallbacksImpl.java:311)
	at com.google.appengine.api.datastore.BaseCallbackContext.executeCallbacks(BaseCallbackContext.java:70)
	at com.google.appengine.api.datastore.DatastoreCallbacksImpl.executeCallbacks(DatastoreCallbacksImpl.java:218)
	at com.google.appengine.api.datastore.DatastoreCallbacksImpl.executePostPutCallbacks(DatastoreCallbacksImpl.java:189)
	at com.google.appengine.api.datastore.PostPutFuture.executeCallbacks(PostPutFuture.java:22)
	at com.google.appengine.api.datastore.PostPutFuture.executeCallbacks(PostPutFuture.java:11)
	at com.google.appengine.api.datastore.PostOpFuture.wrap(PostOpFuture.java:24)
	at com.google.appengine.api.utils.FutureWrapper.wrapAndCache(FutureWrapper.java:56)
	at com.google.appengine.api.utils.FutureWrapper.get(FutureWrapper.java:93)
	at com.google.appengine.api.utils.FutureWrapper.get(FutureWrapper.java:89)
	at com.google.appengine.api.datastore.FutureHelper.getInternal(FutureHelper.java:68)
	at com.google.appengine.api.datastore.FutureHelper.quietGet(FutureHelper.java:32)
	at com.google.appengine.api.datastore.DatastoreServiceImpl.put(DatastoreServiceImpl.java:56)
	at com.google.appengine.datanucleus.WrappedDatastoreService.put(WrappedDatastoreService.java:100)
	at com.google.appengine.datanucleus.EntityUtils.putEntitiesIntoDatastore(EntityUtils.java:759)
	at com.google.appengine.datanucleus.EntityUtils.putEntityIntoDatastore(EntityUtils.java:706)
	at com.google.appengine.datanucleus.DatastorePersistenceHandler.updateObject(DatastorePersistenceHandler.java:429)
	at org.datanucleus.state.JDOStateManager.flush(JDOStateManager.java:3841)
	at org.datanucleus.ObjectManagerImpl.flushInternalWithOrdering(ObjectManagerImpl.java:3888)
	at org.datanucleus.ObjectManagerImpl.flushInternal(ObjectManagerImpl.java:3811)
	at org.datanucleus.ObjectManagerImpl.processNontransactionalAtomicChanges(ObjectManagerImpl.java:1231)
	at org.datanucleus.ObjectManagerImpl.processNontransactionalUpdate(ObjectManagerImpl.java:1196)
	at org.datanucleus.state.AbstractStateManager.setObjectField(AbstractStateManager.java:2189)
	at com.gallatinsystems.framework.domain.BaseDomain.jdoSetlastUpdateDateTime(BaseDomain.java)
	at com.gallatinsystems.framework.domain.BaseDomain.setLastUpdateDateTime(BaseDomain.java:73)
	at com.gallatinsystems.framework.dao.BaseDAO.save(BaseDAO.java:117)
	at org.waterforpeople.mapping.dao.QuestionAnswerStoreDao.save(QuestionAnswerStoreDao.java:296)
	at org.waterforpeople.mapping.app.web.CronCommanderServlet.extractImageFileGeotags(CronCommanderServlet.java:303)
	at org.waterforpeople.mapping.app.web.CronCommanderServlet.doGet(CronCommanderServlet.java:95)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:848)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1772)
	at com.gallatinsystems.framework.servlet.PersistenceFilter.doFilter(PersistenceFilter.java:71)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1759)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:317)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:127)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:91)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:114)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:137)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:111)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:170)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.akvo.flow.rest.security.NewUserRegistrationRedirectFilter.doFilter(NewUserRegistrationRedirectFilter.java:66)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.akvo.flow.rest.security.google.GoogleAuthenticationFilter.doFilter(GoogleAuthenticationFilter.java:90)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:116)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:66)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.akvo.flow.rest.security.RedirectIndexFilter.doFilter(RedirectIndexFilter.java:46)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:214)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:177)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:347)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:263)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1759)
	at com.google.apphosting.utils.servlet.JdbcMySqlConnectionCleanupFilter.doFilter(JdbcMySqlConnectionCleanupFilter.java:60)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1759)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:582)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:524)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
	at com.google.apphosting.runtime.jetty9.ParseBlobUploadHandler.handle(ParseBlobUploadHandler.java:119)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1182)
	at com.google.apphosting.runtime.jetty9.AppEngineWebAppContext.doHandle(AppEngineWebAppContext.java:187)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:512)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at com.google.apphosting.runtime.jetty9.AppVersionHandlerMap.handle(AppVersionHandlerMap.java:293)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
	at org.eclipse.jetty.server.Server.handle(Server.java:539)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:333)
	at com.google.apphosting.runtime.jetty9.RpcConnection.handle(RpcConnection.java:213)
	at com.google.apphosting.runtime.jetty9.RpcConnector.serviceRequest(RpcConnector.java:81)
	at com.google.apphosting.runtime.jetty9.JettyServletEngineAdapter.serviceRequest(JettyServletEngineAdapter.java:134)
	at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.dispatchServletRequest(JavaRuntime.java:757)
	at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.dispatchRequest(JavaRuntime.java:720)
	at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.run(JavaRuntime.java:690)
	at com.google.apphosting.runtime.JavaRuntime$NullSandboxRequestRunnable.run(JavaRuntime.java:882)
	at com.google.apphosting.runtime.ThreadGroupPool$PoolEntry.run(ThreadGroupPool.java:270)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by iperdomo** [comment]
```
2020-03-22 15:30:04.211 CET
com.google.apphosting.runtime.jetty9.JettyLogger warn: /cron/croncommander
Datastore Failure
org.datanucleus.exceptions.NucleusDataStoreException: Datastore Failure
	at com.google.appengine.datanucleus.DatastoreExceptionTranslator.wrapDatastoreFailureException(DatastoreExceptionTranslator.java:50)
	at com.google.appengine.datanucleus.WrappedDatastoreService.put(WrappedDatastoreService.java:106)
	at com.google.appengine.datanucleus.EntityUtils.putEntitiesIntoDatastore(EntityUtils.java:759)
	at com.google.appengine.datanucleus.EntityUtils.putEntityIntoDatastore(EntityUtils.java:706)
	at com.google.appengine.datanucleus.DatastorePersistenceHandler.updateObject(DatastorePersistenceHandler.java:429)
	at org.datanucleus.state.JDOStateManager.flush(JDOStateManager.java:3841)
	at org.datanucleus.ObjectManagerImpl.flushInternalWithOrdering(ObjectManagerImpl.java:3888)
	at org.datanucleus.ObjectManagerImpl.flushInternal(ObjectManagerImpl.java:3811)
	at org.datanucleus.ObjectManagerImpl.processNontransactionalAtomicChanges(ObjectManagerImpl.java:1231)
	at org.datanucleus.ObjectManagerImpl.processNontransactionalUpdate(ObjectManagerImpl.java:1196)
	at org.datanucleus.state.AbstractStateManager.setObjectField(AbstractStateManager.java:2189)
	at com.gallatinsystems.framework.domain.BaseDomain.jdoSetlastUpdateDateTime(BaseDomain.java)
	at com.gallatinsystems.framework.domain.BaseDomain.setLastUpdateDateTime(BaseDomain.java:73)
	at com.gallatinsystems.framework.dao.BaseDAO.save(BaseDAO.java:117)
	at org.waterforpeople.mapping.dao.QuestionAnswerStoreDao.save(QuestionAnswerStoreDao.java:296)
	at org.waterforpeople.mapping.app.web.CronCommanderServlet.extractImageFileGeotags(CronCommanderServlet.java:303)
	at org.waterforpeople.mapping.app.web.CronCommanderServlet.doGet(CronCommanderServlet.java:95)
```
