### ISSUE TITLE
NPE while validating forms as webforms

### ISSUE THREAD

**Issue by muloem** [akvo/akvo-flow#3609]
# Context
While validating webforms, we get an NPE

```java
com.gallatinsystems.framework.dao.BaseDAO getByKey: No com.gallatinsystems.survey.domain.SurveyGroup found with id: *********12 (BaseDAO.java:243)

com.gallatinsystems.framework.rest.AbstractRestApiServlet executeRequest: Could not execute rest request (AbstractRestApiServlet.java:119)
java.lang.NullPointerException
	at com.gallatinsystems.survey.domain.WebForm.validForm(WebForm.java:39)
	at com.gallatinsystems.survey.domain.WebForm.validWebForm(WebForm.java:49)
	at org.waterforpeople.mapping.app.web.SurveyAssemblyServlet.assembleFormWithJackson(SurveyAssemblyServlet.java:201)
	at org.waterforpeople.mapping.app.web.SurveyAssemblyServlet.handleRequest(SurveyAssemblyServlet.java:112)
	at com.gallatinsystems.framework.rest.AbstractRestApiServlet.executeRequest(AbstractRestApiServlet.java:109)
	at com.gallatinsystems.framework.rest.AbstractRestApiServlet.doPost(AbstractRestApiServlet.java:82)
```
# Problem or idea
The wrong value is used to retrieve the Survey.

# Solution or next step

**Comment by janagombitova** [comment]
@muloem if this is completed and released, can you please close? If not, can you comment? thanks
