### ISSUE TITLE
Crash when trying to get assigned datapoints

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow#3652]
# Context
Support request from Ecosia, they are unable to download datapoints even after latest release.
In the logs there is a NPE:
`com.gallatinsystems.framework.rest.AbstractRestApiServlet executeRequest: Could not execute rest request (AbstractRestApiServlet.java:119)
java.lang.NullPointerException
	at java.util.stream.Collectors.lambda$groupingBy$46(Collectors.java:953)
	at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1383)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at org.akvo.flow.api.app.DataPointUtil.getSurveyInstances(DataPointUtil.java:218)
	at org.akvo.flow.api.app.DataPointUtil.getSurveyedLocaleDtosList(DataPointUtil.java:67)
	at org.akvo.flow.api.app.DataPointServlet.convertToResponse(DataPointServlet.java:113)
	at org.akvo.flow.api.app.DataPointServlet.handleRequest(DataPointServlet.java:89)`

It seems that a datapoint has no registration form submission.

**Comment by janagombitova** [comment]
Can we close this now that the changes are released?
