### ISSUE TITLE
Exception when processing files

### ISSUE THREAD

**Issue by muloem** [akvo/akvo-flow#3829]
# Context
When processing submissions from the devices or webforms we get an exception.  it seems to be connected to a change we made where we use a local jar file instead of maven. 

# Problem or idea
```
java.lang.NoClassDefFoundError: com/beoui/geocell/model/Point
	at com.gallatinsystems.surveyal.app.web.SurveyalRestServlet.ingestSurveyInstance(SurveyalRestServlet.java:243)
	at com.gallatinsystems.surveyal.app.web.SurveyalRestServlet.ingestSurveyInstance(SurveyalRestServlet.java:196)
	at com.gallatinsystems.surveyal.app.web.SurveyalRestServlet.handleRequest(SurveyalRestServlet.java:114)
	at com.gallatinsystems.framework.rest.AbstractRestApiServlet.executeRequest(AbstractRestApiServlet.java:109)
	at com.gallatinsystems.framework.rest.AbstractRestApiServlet.doPost(AbstractRestApiServlet.java:82)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:848)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1780)
	at com.gallatinsystems.framework.servlet.PersistenceFilter.doFilter(PersistenceFilter.java:71)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1767)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:320)
```

# Solution or next step
How could we solve it?

**Comment by valllllll2000** [comment]
I wonder if this could be the reason https://github.com/akvo/akvo-flow/blob/9b4f50a8a0a2a76a8e1349bac024e2a21364bc9d/GAE/pom.xml#L213
